### PR TITLE
Fix envelope multiple addresses parsing

### PR DESCRIPTION
**Pull request by maxoly**
Fix envelope parsing for multi-address fields in IMAP

### Motivation:

The current implementation of the envelope parsing logic fails to correctly handle multiple addresses in fields like FROM, TO, CC, and BCC. This is due to the parser not accounting for potential spaces between addresses, leading to failures when encountering envelope fields with more than one address.

### Modifications:

- Updated the email address parsing logic to correctly handle spaces between addresses in multi-address scenarios.
- Updated unit test to cover scenarios with multiple addresses in envelope fields.

### Result:

After this change, envelope fields containing multiple addresses, such as the TO, FROM, CC, and BCC fields, are correctly parsed, regardless of the spacing between addresses.

### CODE REVIEW

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
Hmm, the 5.9 CI failure is a warnings-as-errors issue for a warning in 5.9.

**Review by danieleggert — APPROVED** [review]

**Comment by danieleggert** [comment]
Thanks for the fix! Looks good.

**Comment by danieleggert** [comment]
@swift-server-bot test this please

**Comment by danieleggert** [comment]
@swift-server-bot test this please

**Comment by maxoly** [comment]
@swift-server-bot test this please

**Comment by danieleggert** [comment]
@swift-server-bot test this please

**Pull request merged**
